"""Add GPA model

Revision ID: 4e44d24322bc
Revises: 91a41e52aeaf
Create Date: 2020-12-30 16:25:27.736500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e44d24322bc'
down_revision = '91a41e52aeaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GPA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GPA')
    # ### end Alembic commands ###
