"""add course to grades

Revision ID: 9364342e3ee7
Revises: 2fb9b9a4361e
Create Date: 2021-01-02 15:14:33.891612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9364342e3ee7'
down_revision = '2fb9b9a4361e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_column('course')

    # ### end Alembic commands ###
